# Generated by Django 4.2 on 2023-12-07 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    models.IntegerField(
                        choices=[
                            (1, "Главный"),
                            (2, "Средний"),
                            (3, "Неважный"),
                        ],
                        db_column="point",
                        verbose_name="оценка товара",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        verbose_name="опубликовано",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="дата создания товара",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="дата изменения товара",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="максимально 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="запишите сюда текст заметки",
                        unique=True,
                        verbose_name="текст заметки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority",
                        to="tasks.priority",
                        verbose_name="приоритет",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="task_tags",
                        to="tag.tag",
                        verbose_name="теги",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(),
                ),
                (
                    "priority",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        related_query_name="main_image",
                        to="tasks.priority",
                    ),
                ),
            ],
            options={
                "verbose_name": "главное фото приоритета",
                "verbose_name_plural": "главные фотографии приоритетов",
            },
        ),
    ]


__all__ = ()
