# Generated by Django 4.2 on 2024-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")],
                db_column="priority",
                default=3,
                verbose_name="приоритет",
            ),
        ),
    ]
