# Generated by Django 4.2 on 2023-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_created_at_alter_task_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="text",
            field=models.TextField(
                help_text="Запишите сюда текст заметки",
                verbose_name="текст заметки",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.TextField(
                help_text="Максимально 150 символов",
                max_length=150,
                verbose_name="название",
            ),
        ),
    ]


__all__ = ()
