# Generated by Django 4.2 on 2023-12-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_text_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priority",
                to="tasks.priority",
                verbose_name="приоритет",
            ),
        ),
    ]


__all__ = ()
