# Generated by Django 4.2 on 2023-12-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_alter_tag_name"),
        ("tasks", "0004_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priority",
                to="tasks.priority",
                verbose_name="приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="task_tags",
                to="tag.tag",
                verbose_name="теги",
            ),
        ),
    ]


__all__ = ()
