# Generated by Django 4.2 on 2023-12-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_priority_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Главный"), (2, "Средний"), (3, "Неважный")],
                db_column="priority",
                default=3,
                verbose_name="приоритет",
            ),
        ),
        migrations.DeleteModel(
            name="MainImage",
        ),
        migrations.DeleteModel(
            name="Priority",
        ),
    ]


__all__ = ()
