# Generated by Django 4.2 on 2023-12-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_task_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="Запишите сюда текст заметки",
                null=True,
                verbose_name="текст заметки",
            ),
        ),
    ]


__all__ = ()
