# Generated by Django 4.2 on 2023-12-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

__all__ = ()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="создатель",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(
                help_text="Запишите сюда текст заметки",
                unique=True,
                verbose_name="текст заметки",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.TextField(
                help_text="Максимально 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="дата изменения",
            ),
        ),
    ]
