# Generated by Django 4.2 on 2023-12-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_alter_note_created_at_alter_note_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(
                help_text="Запишите сюда текст заметки",
                verbose_name="текст заметки",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.TextField(
                help_text="Максимально 150 символов",
                max_length=150,
                verbose_name="название",
            ),
        ),
    ]


__all__ = ()
