# Generated by Django 4.2 on 2023-12-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_alter_tag_name"),
        ("notes", "0003_alter_note_text_alter_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="note_tags",
                to="tag.tag",
                verbose_name="теги",
            ),
        ),
    ]


__all__ = ()
