# Generated by Django 4.2 on 2023-12-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

__all__ = ()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0002_alter_note_created_at_alter_note_owner_and_more"),
        ("tasks", "0002_alter_task_created_at_alter_task_owner_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="участники проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(
                help_text="Максимально 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.note",
                verbose_name="заметки",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="создатель",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.task",
                verbose_name="задачи",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="дата изменения",
            ),
        ),
    ]
