# Generated by Django 4.2 on 2023-12-10 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_note_text_alter_note_title"),
        ("tasks", "0003_alter_task_text_alter_task_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "projects",
            "0002_alter_project_created_at_alter_project_members_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="members",
        ),
        migrations.RemoveField(
            model_name="project",
            name="note",
        ),
        migrations.RemoveField(
            model_name="project",
            name="task",
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="участники проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="note",
            field=models.ManyToManyField(
                related_name="notes",
                to="notes.note",
                verbose_name="заметки",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="task",
            field=models.ManyToManyField(
                related_name="tasks",
                to="tasks.task",
                verbose_name="задачи",
            ),
        ),
    ]


__all__ = ()
