# Generated by Django 4.2 on 2023-12-09 10:39

from django.db import migrations, models

__all__ = ()


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="Максимально 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
    ]
