# Generated by Django 4.2 on 2023-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                db_column="attempts_count",
                default=0,
                verbose_name="попыток войти в аккаунт",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="blocked_time",
            field=models.DateTimeField(
                blank=True,
                db_column="user_freeze",
                null=True,
                verbose_name="дата заморозки",
            ),
        ),
    ]


__all__ = ()
