# Generated by Django 4.2 on 2023-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_attempts_count_profile_blocked_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirm",
            field=models.BooleanField(
                blank=True,
                db_column="email_confirm",
                default=False,
                verbose_name="активация почты",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                blank=True,
                db_column="attempts_count",
                default=0,
                verbose_name="попыток войти в аккаунт",
            ),
        ),
    ]


__all__ = ()
